vich_uploader:
    db_driver: orm

    mappings:
        concept_image:
                uri_prefix: /upload/concept
                upload_destination: '%kernel.project_dir%/public/upload/concept'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
